### ISSUE TITLE
Toggle sound effects

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#1]
## ⛰ Background

The player should be able to turn off/on sound effects

## 📄 Tasks

- [ ] Create speaker-button
- [ ] Create enabled/disabled icon
- [ ] Implement functional code

## 🤺 User story

As a player
I want to toggle sound effects
By clicking a button

**Comment by LiviaValenti** [comment]
Closed because of duplicate #10
