### ISSUE TITLE
Create settings functionality

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#10]
## ⛰ Background

The player should be able to toggle audio, read the tutorial or quit the game from the game view.

## 📄 Tasks

- [x] Create setting button on game view
- [ ] Create speaker-button
    - [ ] Create enabled/disabled icon
    - [ ] Implement functionality for audio toggle
- [x] Create quit-button on popup (with functionality)
- [x] Create read tutorial-button on popup (with functionality)

## 🤺 User story

As a player
I want to be able to access settings from the game view
