### ISSUE TITLE
Create gameloop

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#11]
## ⛰ Background

The game is round-based where you win the game by getting best of three. When a player wins a round, their score is incremented and a countdown to a new round is shown unless the player has won.

## 📄 Tasks

- [x] Create a Game class 
    - [x] Score counters for the players involved
    - [x] Round counter
- [x] If a player wins a round, show a countdown and start a new round
    - [x] Increment score for given player
- [x] If a player wins (best of 3)
    - [x] Show winning-screen
    - [x] Increment character score
    - [x] Redirect to scoreboard

## 🤺 User story

As a player
I want to be able to win the game
By winning best of three
