### ISSUE TITLE
Player movement

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#4]
## ⛰ Background

If the player presses their button, they should move one step forward

## 📄 Tasks

- [x] Each player should start on their half of the ring
- [x] Create fist-button
- [ ] Create button feedback animation on tap
- [x] Logic to move character one step forward on tap

## 🤺 User story

As a player
I want to move the character one step when I tap
So that it moves forward
