### ISSUE TITLE
Player collision

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#6]
## ⛰ Background

If the players are in contact and the player presses their button, they should move the opponent one step backward. If a player presses their button _x_ times more than the other player, they push the other player out of the ring and wins the current round (#11).

## 📄 Tasks

- [x] Add player boundary
- [x] Detect collision
- [x] Implement pushback
- [x] Add arena boundary
- [x] Detect exit of arena boundary

## 🤺 User story

As a player
I want to collide with my opponent
To push them out of the arena
