### ISSUE TITLE
Character selection

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#7]
## ⛰ Background

The player should be able to select different playable characters.

## 📄 Tasks

- [x] Create character class
- [x] Create character selection menu
- [x] Add sprites for different characters
- [x] Add chosen sprite to given player
- [x] Display selected sprite according to Figma (give player feedback)
- [x] Graphics: buttons to go back home and to BATTLE TAP!

## 🤺 User story

As a player
I want to be able to choose a character
So that play as it
