### ISSUE TITLE
Create scoreboard

### ISSUE THREAD

**Issue by LiviaValenti** [LiviaValenti/TDT4240-sumo-battle-tap#9]
## ⛰ Background

The characters should have an online aggregated score, based on the players points. This entails creating a database, character documents (or scoreboard document depending on chosen architecture), create a method to increment the score for a given character and retrieval of all scores. 

## 📄 Tasks

- [x] Set up 🔥base
- [x] Set up scoreboard structure in 🔥base
- [x] Create method from game to increment score for given character
- [x] Retrieve scores from database
- [ ] Display scores on scoreboard screen

## 🤺 User story

As a player
I want to see the scoreboard
